#!/bin/bash

# VTA Station API Checker
# Checks if each station stop code returns valid data from 511.org API

API_KEY="cfc3474b-61e1-48f4-a177-0c8b8cb27cca"
BASE_URL="https://api.511.org/transit/StopMonitoring"

check_stop() {
    local stop_code=$1
    local station_name=$2
    local line=$3
    
    response=$(curl -s "${BASE_URL}?api_key=${API_KEY}&agency=SC&stopCode=${stop_code}&format=json" 2>/dev/null)
    
    # Check if response contains MonitoredStopVisit (even if empty array)
    if echo "$response" | grep -q "MonitoredStopVisit"; then
        # Check if there's actual data
        if echo "$response" | grep -q '"MonitoredStopVisit":\[\]'; then
            echo "⚠️  $line | $station_name ($stop_code): No trains (empty)"
        else
            echo "✅ $line | $station_name ($stop_code): OK"
        fi
    elif echo "$response" | grep -q "error"; then
        echo "❌ $line | $station_name ($stop_code): API Error"
    else
        echo "❓ $line | $station_name ($stop_code): Unknown response"
    fi
}

echo "=== Checking Orange Line Stations ==="
# Orange Line (E/W directions)
check_stop "64786" "Mountain View (E)" "Orange"
check_stop "64821" "Mountain View (W)" "Orange"
check_stop "64788" "Whisman (E)" "Orange"
check_stop "64819" "Whisman (W)" "Orange"
check_stop "64789" "Middlefield (E)" "Orange"
check_stop "64818" "Middlefield (W)" "Orange"
check_stop "64790" "Bayshore/NASA (E)" "Orange"
check_stop "64817" "Bayshore/NASA (W)" "Orange"
check_stop "65024" "Moffett Park (E)" "Orange"
check_stop "65025" "Moffett Park (W)" "Orange"
check_stop "64791" "Lockheed Martin (E)" "Orange"
check_stop "64816" "Lockheed Martin (W)" "Orange"
check_stop "64792" "Borregas (E)" "Orange"
check_stop "64815" "Borregas (W)" "Orange"
check_stop "64793" "Crossman (E)" "Orange"
check_stop "64814" "Crossman (W)" "Orange"
check_stop "64794" "Fair Oaks (E)" "Orange"
check_stop "64813" "Fair Oaks (W)" "Orange"
check_stop "64795" "Vienna (E)" "Orange"
check_stop "64812" "Vienna (W)" "Orange"
check_stop "64796" "Reamwood (E)" "Orange"
check_stop "64811" "Reamwood (W)" "Orange"
check_stop "64797" "Old Ironsides (E)" "Orange"
check_stop "64810" "Old Ironsides (W)" "Orange"
check_stop "64798" "Great America (E)" "Orange"
check_stop "64809" "Great America (W)" "Orange"
check_stop "64799" "Lick Mill (E)" "Orange"
check_stop "64808" "Lick Mill (W)" "Orange"
check_stop "64800" "Champion (E)" "Orange"
check_stop "64807" "Champion (W)" "Orange"
check_stop "64801" "Baypointe (E)" "Orange"
check_stop "64806" "Baypointe (W)" "Orange"
check_stop "64802" "Cisco Way (E)" "Orange"
check_stop "64805" "Cisco Way (W)" "Orange"
check_stop "64803" "Alder (E)" "Orange"
check_stop "64804" "Alder (W)" "Orange"
check_stop "65235" "Great Mall (E)" "Orange"
check_stop "65250" "Great Mall (W)" "Orange"
check_stop "65236" "Milpitas (E)" "Orange"
check_stop "65249" "Milpitas (W)" "Orange"
check_stop "65237" "Cropley (E)" "Orange"
check_stop "65248" "Cropley (W)" "Orange"
check_stop "65238" "Hostetter (E)" "Orange"
check_stop "65247" "Hostetter (W)" "Orange"
check_stop "65239" "Berryessa (E)" "Orange"
check_stop "65246" "Berryessa (W)" "Orange"
check_stop "65240" "Penitencia Creek (E)" "Orange"
check_stop "65245" "Penitencia Creek (W)" "Orange"
check_stop "65241" "McKee (E)" "Orange"
check_stop "65244" "McKee (W)" "Orange"
check_stop "65242" "Alum Rock (E)" "Orange"
check_stop "65243" "Alum Rock (W)" "Orange"

echo ""
echo "=== Checking Blue Line Stations ==="
# Blue Line (N/S directions)
check_stop "64801" "Baypointe (N)" "Blue"
check_stop "64806" "Baypointe (S)" "Blue"
check_stop "64762" "Tasman (N)" "Blue"
check_stop "64763" "Tasman (S)" "Blue"
check_stop "64758" "River Oaks (N)" "Blue"
check_stop "64759" "River Oaks (S)" "Blue"
check_stop "64764" "Orchard (N)" "Blue"
check_stop "64765" "Orchard (S)" "Blue"
check_stop "64770" "Bonaventura (N)" "Blue"
check_stop "64771" "Bonaventura (S)" "Blue"
check_stop "64768" "Component (N)" "Blue"
check_stop "64769" "Component (S)" "Blue"
check_stop "64766" "Karina (N)" "Blue"
check_stop "64767" "Karina (S)" "Blue"
check_stop "64772" "Metro/Airport (N)" "Blue"
check_stop "64773" "Metro/Airport (S)" "Blue"
check_stop "64774" "Gish (N)" "Blue"
check_stop "64775" "Gish (S)" "Blue"
check_stop "64776" "Civic Center (N)" "Blue"
check_stop "64777" "Civic Center (S)" "Blue"
check_stop "64778" "Japantown/Ayer (N)" "Blue"
check_stop "64779" "Japantown/Ayer (S)" "Blue"
check_stop "64780" "St. James (N)" "Blue"
check_stop "64781" "St. James (S)" "Blue"
check_stop "64782" "Santa Clara (N)" "Blue"
check_stop "64783" "Santa Clara (S)" "Blue"
check_stop "64784" "Paseo de San Antonio (N)" "Blue"
check_stop "64785" "Paseo de San Antonio (S)" "Blue"
check_stop "64824" "Convention Center (N)" "Blue"
check_stop "64825" "Convention Center (S)" "Blue"
check_stop "64826" "San Fernando (N)" "Blue"
check_stop "64827" "San Fernando (S)" "Blue"
check_stop "64828" "Virginia (N)" "Blue"
check_stop "64829" "Virginia (S)" "Blue"
check_stop "64830" "Tamien (N)" "Blue"
check_stop "64831" "Tamien (S)" "Blue"
check_stop "64832" "Curtner (N)" "Blue"
check_stop "64833" "Curtner (S)" "Blue"
check_stop "64834" "Capitol (N)" "Blue"
check_stop "64835" "Capitol (S)" "Blue"
check_stop "64836" "Branham (N)" "Blue"
check_stop "64837" "Branham (S)" "Blue"
check_stop "64838" "Ohlone/Chynoweth (N)" "Blue"
check_stop "64839" "Ohlone/Chynoweth (S)" "Blue"
check_stop "64840" "Blossom Hill (N)" "Blue"
check_stop "64841" "Blossom Hill (S)" "Blue"
check_stop "64842" "Snell (N)" "Blue"
check_stop "64843" "Snell (S)" "Blue"
check_stop "64844" "Cottle (N)" "Blue"
check_stop "64845" "Cottle (S)" "Blue"
check_stop "64846" "Santa Teresa (N)" "Blue"
check_stop "64847" "Santa Teresa (S)" "Blue"

echo ""
echo "=== Checking Green Line Stations ==="
# Green Line (N/S directions)
check_stop "64797" "Old Ironsides (N)" "Green"
check_stop "64810" "Old Ironsides (S)" "Green"
check_stop "64796" "Reamwood (N)" "Green"
check_stop "64811" "Reamwood (S)" "Green"
check_stop "64795" "Vienna (N)" "Green"
check_stop "64812" "Vienna (S)" "Green"
check_stop "64794" "Fair Oaks (N)" "Green"
check_stop "64813" "Fair Oaks (S)" "Green"
check_stop "64793" "Crossman (N)" "Green"
check_stop "64814" "Crossman (S)" "Green"
check_stop "64792" "Borregas (N)" "Green"
check_stop "64815" "Borregas (S)" "Green"
check_stop "64762" "Tasman (N)" "Green"
check_stop "64763" "Tasman (S)" "Green"
check_stop "64766" "Karina (N)" "Green"
check_stop "64767" "Karina (S)" "Green"
check_stop "64768" "Component (N)" "Green"
check_stop "64769" "Component (S)" "Green"
check_stop "64770" "Bonaventura (N)" "Green"
check_stop "64771" "Bonaventura (S)" "Green"
check_stop "64772" "Metro/Airport (N)" "Green"
check_stop "64773" "Metro/Airport (S)" "Green"
check_stop "64774" "Gish (N)" "Green"
check_stop "64775" "Gish (S)" "Green"
check_stop "64776" "Civic Center (N)" "Green"
check_stop "64777" "Civic Center (S)" "Green"
check_stop "64778" "Japantown/Ayer (N)" "Green"
check_stop "64779" "Japantown/Ayer (S)" "Green"
check_stop "64780" "St. James (N)" "Green"
check_stop "64781" "St. James (S)" "Green"
check_stop "64782" "Santa Clara (N)" "Green"
check_stop "64783" "Santa Clara (S)" "Green"
check_stop "64784" "Paseo de San Antonio (N)" "Green"
check_stop "64785" "Paseo de San Antonio (S)" "Green"
check_stop "64824" "Convention Center (N)" "Green"
check_stop "64825" "Convention Center (S)" "Green"
check_stop "64826" "San Jose Diridon (N)" "Green"
check_stop "64827" "San Jose Diridon (S)" "Green"
check_stop "64828" "San Fernando (N)" "Green"
check_stop "64829" "San Fernando (S)" "Green"
check_stop "64848" "Children's Discovery Museum (N)" "Green"
check_stop "64849" "Children's Discovery Museum (S)" "Green"
check_stop "64850" "Race (N)" "Green"
check_stop "64851" "Race (S)" "Green"
check_stop "64852" "Fruitdale (N)" "Green"
check_stop "64853" "Fruitdale (S)" "Green"
check_stop "64854" "Bascom (N)" "Green"
check_stop "64855" "Bascom (S)" "Green"
check_stop "64856" "Hamilton (N)" "Green"
check_stop "64857" "Hamilton (S)" "Green"
check_stop "64858" "Downtown Campbell (N)" "Green"
check_stop "64859" "Downtown Campbell (S)" "Green"
check_stop "64860" "Winchester (N)" "Green"
check_stop "64861" "Winchester (S)" "Green"

echo ""
echo "=== Done ==="
